apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx-service
spec: 
  type: NodePort
  ports: 
    - port: 80
      name: http
    - port: 443
      name: https
  selector: 
    app: nginxpod