---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-app-sot
spec:
  interval: 30s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx-app-sot
